- .travis.yml
- pytest.ini
- tests/end2end/features/misc/clipboard.feature
- tests/end2end/features/misc/test_clipboard_bdd.py
- vimiv/gui/image.py
- vimiv/imutils/immanipulate.py
> Travis for CI

- misc/Makefile
- misc/vimiv.appdata.xml
Also adds required bits in the Makefile
NOTE: the appdata file may need tweaks once vimiv-qt replaces vimiv.
Fixes #3
> Adds appdata file

- tests/unit/utils/test_crash_handler.py
- tox.ini
- vimiv/app.py
- vimiv/utils/crash_handler.py
- vimiv/vimiv.py
Add a handler for uncaught exceptions and signals.
> Crash handler

- docs/documentation/getting_started.rst
- scripts/pylint_checkers/check_docstring.py
- tests/end2end/features/api/mark.feature
- tests/end2end/features/api/test_mark_bdd.py
- tests/end2end/features/conftest.py
- tests/end2end/vimivprocess.py
- tests/unit/api/test_mark.py
- tests/unit/utils/test_utils.py
- vimiv/api/__init__.py
- vimiv/api/_mark.py
- vimiv/api/settings.py
- vimiv/commands/runners.py
- vimiv/config/styles.py
- vimiv/gui/library.py
- vimiv/gui/manipulate.py
- vimiv/gui/thumbnail.py
- vimiv/utils/__init__.py
This implements support for marks and tags including commands, status modules and visual indications for currently marked images.
fixes #5
> Marks and tags

- tests/end2end/features/completion/completion.feature
- vimiv/api/completion.py
- vimiv/api/settings.py
- vimiv/completion/completionmodels.py
- vimiv/gui/commandline.py
> Add option for fuzzy completion filtering

- .travis.yml
- tox.ini
This adds PyQt 5.13 to tox, updates the version of PyQt 5.12 and removes the unused 5.7 component.
> Update PyQt versions

- tests/end2end/features/completion/completion.feature
- vimiv/api/completion.py
- vimiv/api/modes.py
- vimiv/completion/completer.py
- vimiv/completion/completionmodels.py
> Mode dependent completion

- docs/changelog.rst
- pytest.ini
- tests/conftest.py
- tests/end2end/features/config/configcommands.feature
- tests/end2end/features/config/test_configcommands_bdd.py
- tests/end2end/features/conftest.py
- tests/integration/__init__.py
- tests/integration/conftest.py
- tests/integration/test_read_bindings.py
- tests/integration/test_read_settings.py
- tests/unit/config/test_config.py
- tests/unit/config/test_styles.py
- vimiv/config/__init__.py
- vimiv/config/configfile.py
- vimiv/config/keyfile.py
- vimiv/config/styles.py
- vimiv/startup.py
This includes:
* Small refactoring of config related modules to improve unification and testability
* Integration and unit tests for config file reading
> Improve test situation of the config module

- tests/end2end/features/image/imagezoom.feature
- tests/end2end/features/image/test_imagedelete_bdd.py
- tests/end2end/features/image/test_imagefit_bdd.py
- tests/end2end/features/image/test_imagezoom_bdd.py
- vimiv/gui/image.py
This significantly improves zooming and scaling performance and includes some improved mouse support for image mode.
> Use graphicsview for image widget

- docs/changelog.rst
- docs/documentation/hacking.rst
- tests/end2end/features/api/modeswitch.feature
- tests/end2end/features/commandline/test_commandline_bdd.py
- tests/end2end/features/completion/completion.feature
- tests/end2end/features/completion/test_completion_bdd.py
- tests/end2end/features/conftest.py
- vimiv/api/_modules.py
- vimiv/api/completion.py
- vimiv/completion/completer.py
- vimiv/completion/completionmodels.py
- vimiv/gui/bar.py
- vimiv/gui/completionwidget.py
* Remove need of a `BaseFilter` by using a proper regular expression for completion filtering.
* Show/hide completion widget depending on if there are completions available.
* Improve clarity of dependencies.
* Minor improvements such as the use of generator expressions.
> Refactor completion

- docs/changelog.rst
- tests/end2end/features/conftest.py
- tests/end2end/features/image/slideshow.feature
- vimiv/gui/image.py
Next try on 5d624912d9362165cf0120aa6182c125b844453b, now with a test
and catching some more corner cases.
> Stop slideshow when image is unfocused

- docs/changelog.rst
- tests/end2end/features/commandline/commandline.feature
- tests/end2end/features/commandline/test_commandline_bdd.py
- vimiv/api/__init__.py
- vimiv/api/_help.py
- vimiv/api/_modules.py
- vimiv/completion/completionmodels.py
- vimiv/gui/statusbar.py
* Nicer formatting using the html-subset of `QLabel`
* New topic for wildcards
* Split logic into own module
> Improvements to the :help command

- docs/changelog.rst
- tests/end2end/conftest.py
- tests/end2end/features/completion/completion.feature
- tests/end2end/features/image/imagedelete.feature
- vimiv/api/completion.py
- vimiv/utils/trash_manager.py
fixes #228
This will be followed up by some refactoring of `utils.trash_manager`.
> Fix percent issues

- docs/changelog.rst
- tests/end2end/features/completion/completion.feature
- tests/end2end/features/completion/test_completion_bdd.py
- vimiv/completion/completionmodels.py
- vimiv/utils/trash_manager.py
@woefe could you give this a quick check before I merge?
fixes #240
> Fix compliance with the xdg trash standard

- AUTHORS
- docs/changelog.rst
- docs/documentation/configuration/plugins.rst
- docs/documentation/hacking.rst
I am very sorry but I had to change my github username. I have updated all references to it. I hope this is alright :grimacing:
> Change username and all references

- docs/changelog.rst
- tests/end2end/features/library/libraryscroll.feature
- tests/end2end/features/library/test_libraryscroll_bdd.py
- tests/end2end/features/thumbnail/thumbnailscroll.feature
- vimiv/commands/argtypes.py
- vimiv/gui/library.py
- vimiv/gui/thumbnail.py
- vimiv/widgets.py
Implements additional vim movement commands as proposed in #295.
As you came up with the idea, would you like to give this a test and check if this is what you had in mind before I merge @jcjgraf?
fixes #295.
> More vim movements

- vimiv/commands/delete_command.py
Let me know if you prefere to fix this somehow differently.
Fixes #330
> Crash on Deletion Without Permissions

- .pylintrc
- fastentrypoints.py
- scripts/rstutils.py
- scripts/src2rst.py
- scripts/vimiv_history.py
- setup.py
- tests/integration/conftest.py
- tests/unit/api/test_mark.py
- tests/unit/commands/test_history.py
- tests/unit/config/test_external_configparser.py
- tests/unit/config/test_styles.py
- tests/unit/utils/test_migration.py
- tests/unit/utils/test_trash_manager.py
- vimiv/api/_mark.py
- vimiv/commands/history.py
- vimiv/config/configfile.py
- vimiv/config/keyfile.py
- vimiv/config/styles.py
> adds encoding="utf-8" everywhere

- tests/end2end/conftest.py
- tests/end2end/features/image/imagescroll.feature
- tests/end2end/features/image/test_imagescroll_bdd.py
- tests/end2end/features/misc/startup.feature
Just a few more straightforward end2end tests, checking the impact on the new codecov jobs.
> Add a few more tests

- docs/changelog.rst
- tests/end2end/features/statusbar/status.feature
- tests/end2end/features/statusbar/test_status_bdd.py
- vimiv/gui/image.py
See #8 for the rationale behind this.
> Add statusbar module for cursor position in image coordinates

- docs/documentation/configuration/keybindings.rst
- vimiv/config/configcommands.py
As I noticed on #647, updating the documentation about toggling bool setting.
Hope I'm not missing something. Again.
If the wording is bad, we can update it. I'm not english speaker, so sorry if anything sounds strange.
> Improve the documentation

- .github/workflows/ci.yml
- docs/documentation/install.rst
- setup.py
- tox.ini
- vimiv/api/modes.py
- vimiv/checkversion.py
fixes #656 
As described in 135dc28d9442f6c0e41b99d82636d850ea314995, Protocols are unfortunately not enough as we also need the `_ModeWidget` to **be** a `QWidget`.
> Drop python37

- tests/integration/test_app.py
- vimiv/config/_style_options.py
- vimiv/gui/library.py
fixes #840 as described by using the style correctly in the library delegate
> Fix library selected fg
