karlch/vimiv-qt

tests/end2end/features/misc/keyhint.feature
tests/end2end/features/misc/test_keyhint_bdd.py
tox.ini
vimiv/api/keybindings.py
vimiv/api/settings.py
vimiv/config/configfile.py
vimiv/config/styles.py
vimiv/gui/keyhint_widget.py
vimiv/gui/mainwindow.py
vimiv/gui/partial_overlay.py
vimiv/utils/eventhandler.py

The keyhint widget displays possible keybindings to complete partial matches, e.g. `gg  goto 1` after pressing `g`. This allows for better discoverability for more complicated chained keybindings.
Here is a screenshot of it in action:

Introduce keyhint widget

---

tests/end2end/features/image/imageopen.feature
tests/end2end/features/image/test_imageopen_bdd.py
tests/unit/utils/test_files.py
vimiv/imutils/_file_handler.py
vimiv/utils/files.py

Use the `imghdr` module to detect valid images and their file format instead of `QImageReader.canRead` to get rid of errors when opening invalid files such as `.tar.gz` files.

Fix false positives in is_image

---

tests/unit/imutils/test_exif.py
vimiv/imutils/__init__.py
vimiv/imutils/_file_handler.py
vimiv/imutils/exif.py
vimiv/imutils/filelist.py

By implementing an exif module the exif orientation is now reset when saving an image file using autowrite or the `:write` command. The module helps keep the exif related code in one place and is thus also the only module requiring the optional dependency piexif.
fixes #51

Fix exif writing

---

docs/documentation/getting_started.rst
tests/end2end/features/command/search.feature
tests/end2end/features/command/test_search_bdd.py
tests/end2end/features/image/conftest.py
tests/end2end/features/image/imageopen.feature
tests/end2end/features/image/test_imagedelete_bdd.py
tests/end2end/features/image/test_imageopen_bdd.py
tests/unit/utils/test_utils.py
vimiv/api/commands.py
vimiv/app.py
vimiv/commands/runners.py
vimiv/commands/search.py
vimiv/startup.py
vimiv/utils/__init__.py
vimiv/utils/clipboard.py

This adds support for unix-style pattern matching for commands that support paths as argument (currently only `:open`) and searching.

Unix style pattern matching

---

docs/changelog.rst
docs/documentation/configuration/style.rst
tests/unit/config/test_styles.py
vimiv/config/styles.py

This makes it easier to create custom styles and keeping them up-to-date as:
* All styles are now based on base16, the 16 style colors is the only thing that custom styles **MUST** supply
And therefore:
* The custom styles do **NOT** have to supply **ALL** of the style options but can focus on the base colors
* Can provide additional customization for specific options
* Don't break with newly introduced style options

Easier custom styles

---

docs/changelog.rst
tests/end2end/features/image/metadata.feature
tests/end2end/features/image/test_metadata_bdd.py
vimiv/config/styles.py
vimiv/gui/mainwindow.py
vimiv/gui/metadata_widget.py
vimiv/imutils/exif.py

This adds:
* The `:metadata` command which toggles an overlay widget in image mode showing basic exif information
* A new keybinding `i` in image mode bound to the `:metadata` command
The information displayed in the widget is still very basic and can be extend in further commits. For this a new issue will be opened.
fixes #17

Add command to show image exif metadata

---

docs/changelog.rst
tests/end2end/features/completion/completion.feature
tests/end2end/features/completion/test_completion_bdd.py
tests/unit/utils/test_files.py
vimiv/api/_mark.py
vimiv/completion/completionmodels.py
vimiv/utils/files.py

This implements tag name completion for the ``:tag-delete``, ``tag-load`` and ``tag-write`` commands.

Tag name completion for :tag-* commands

---

tests/end2end/features/command/chaining.feature
tests/end2end/features/command/test_chaining_bdd.py
tests/unit/utils/test_utils.py
vimiv/commands/aliases.py
vimiv/commands/runners.py
vimiv/utils/__init__.py

This allows chaining multiple commands using ``&&``.
Useful examples:
```
:write && quit
:fullscreen && set statusbar.show!
```
Aliasing to chained commands is possible even recursively. Unfortunately the alias ``tag-open`` is still not very useful as the remaining argument, namely the tag NAME, would require to be in the middle of the alias (``tag-load NAME && open %m``) which is not supported by simple aliases.
fixes #73

Command chaining

---

docs/changelog.rst
tests/unit/utils/test_task.py
vimiv/api/working_directory.py
vimiv/utils/task.py

The new `utils.task` module allows turning functions into tasks which can call non-GUI blocking functions. First use-case of this is to no longer block the GUI when processing working directory changes. Can be useful for further IO bound options.

Tasks for non-GUI blocking function calls

---

.travis.yml
tests/end2end/features/conftest.py

Adds python3.8 to the standard travis CI and fixes a trivial integer conversion warning.

Add python3.8 to travis

---

docs/changelog.rst
docs/documentation/getting_started.rst
tests/end2end/features/misc/keybindings_popup.feature
tests/end2end/features/misc/test_keybindings_popup_bdd.py
tests/unit/utils/test_utils.py
vimiv/config/styles.py
vimiv/gui/keybindings_popup.py
vimiv/gui/library.py
vimiv/gui/mainwindow.py
vimiv/gui/version_popup.py
vimiv/utils/__init__.py
vimiv/widgets.py

The `:keybindings` command displays a pop-up window with the keybindings valid for the current mode. In addition it is searchable, search matches are highlighted and a description is shown for matching commands.
fixes #97

Add keybindings command

---

docs/changelog.rst
setup.py
tests/end2end/features/commandline/commandline.feature
tests/end2end/features/commandline/test_commandline_bdd.py
tests/end2end/features/completion/completion.feature
tests/end2end/features/completion/test_completion_bdd.py
vimiv/__init__.py
vimiv/api/_modules.py
vimiv/completion/completionmodels.py
vimiv/gui/version_popup.py

The `:help` command displays information on commands, settings or a general description in the statusbar. It comes with its own completion model.

Implement :help command

---

docs/documentation/configuration/settings.rst
docs/documentation/configuration/style.rst
tests/unit/config/test_external_configparser.py
vimiv/config/configfile.py
vimiv/config/external_configparser.py
vimiv/config/styles.py

Implements a custom configparser interpolation to allow referring to external resources via `${RESOURCE:variable}`. Currently only `${env:VARIABLE}` is implemented for environment variables, but extending is simple and can be used for #113.

Reference external resources in config file

---

docs/changelog.rst
docs/documentation/configuration/keybindings.rst
tests/end2end/features/misc/test_keyhint_bdd.py
tests/unit/gui/test_eventhandler.py
vimiv/gui/commandline.py
vimiv/gui/eventhandler.py
vimiv/gui/image.py
vimiv/gui/keyhint_widget.py
vimiv/gui/library.py
vimiv/gui/manipulate.py
vimiv/gui/thumbnail.py

Adds support for binding mouse clicks and mouse double clicks to commands. This works the same way as for keybindings, the relevant names are:
* `<button-NAME>`
* `<double-button-NAME>`
where `NAME` is the name of the mouse button, e.g. `left`.
This solves parts of #47 but does not add any mouse bindings.

Mouse click and double click binding support

---

docs/changelog.rst
docs/documentation/commands.rst
docs/documentation/configuration/style.rst
docs/documentation/index.rst
docs/documentation/migrating.rst
tests/end2end/features/misc/migration_popup.feature
tests/end2end/features/misc/test_migration_popup_bdd.py
tests/unit/utils/test_migration.py
vimiv/gui/mainwindow.py
vimiv/startup.py
vimiv/utils/migration.py

This includes some tools and mainly documentation to aid migrating from the gtk version to this qt port. Namely:
* A dedicated page on the website for migrating
* Automatic backup of the gtk vimiv directories
* Automatic migration of tags to their new location
* A welcoming pop-up with the relevant information and links to the full docs
Ideally this should have been done much earlier, but it never came to my mind. Shame on me :sweat_smile:

Better help with migrating from gtk

---

docs/changelog.rst
tests/end2end/features/library/libraryscroll.feature
tests/unit/commands/test_commands.py
vimiv/api/commands.py
vimiv/commands/__init__.py
vimiv/gui/library.py
vimiv/gui/thumbnail.py
vimiv/imutils/filelist.py

* `:goto` now consistently uses the modulo operator in all modes if the passed number is larger than the allowed maximum
* `:goto` can now be run with count only, e.g. `:2goto`
fixes #151

:goto improvements

---

tests/end2end/features/edit/test_transform_bdd.py
tests/end2end/features/edit/transform.feature
tests/unit/imutils/test_imtransform.py
tests/unit/utils/test_utils.py
vimiv/api/commands.py
vimiv/imutils/imtransform.py
vimiv/utils/__init__.py

This PR consists of multiple parts related to transformations:
* Refactor transformation class to:
* Remove a bunch of unneeded attributes
* Simplify check for changed
* Implement new `:rescale` and `:resize` commands to change the dimensions of the original image. These are transformations and therefore can be written to file.
* New `:undo-transformations` command to reset the image to the original.
* Add unit and end2end tests accordingly.

Refactor and add transformations

---

tests/unit/utils/test_utils.py
vimiv/api/commands.py
vimiv/utils/__init__.py

With [pep 563](https://www.python.org/dev/peps/pep-0563/) annotations will be evaluated on demand, not directly. This means they are stored as string and we cannot use them directly. Instead we call `typing.get_type_hints(...)`. This PR updates
* the `utils.slot` decorator and
* the `api.commands.register` decorator
to use `typing.get_hints` appropriately.

Update decorators using type annotations for pep563

---

docs/changelog.rst
tests/integration/test_read_settings.py
tests/unit/api/test_settings.py
vimiv/api/settings.py
vimiv/gui/thumbnail.py

Refactor `api.settings` to remove some of the unnecessarily difficult parts. Fixed a bug and docstrings on-the-fly.

Refactor api.settings

---

docs/changelog.rst
tests/end2end/features/edit/conftest.py
tests/end2end/features/edit/straighten.feature
tests/end2end/features/edit/test_straighten_bdd.py
tests/end2end/features/edit/test_transform_bdd.py
tests/unit/imutils/test_imtransform.py
vimiv/api/settings.py
vimiv/config/_style_options.py
vimiv/gui/image.py
vimiv/gui/straighten_widget.py
vimiv/gui/transform_widget.py
vimiv/imutils/imtransform.py

Implements a new `:straighten` command which displays a grid to straighten images.
The image is rotated clockwise with `l`, `>` or `L` and counter-clockwise with `h`, `<` or `H`. Changes are accepted with `<return>` and discarded with `<escape>`. This comes with the new `{transformation-info}` status module which displays the current angle when straightening.
Here is a picture of the whole implementation in action:

Add :straighten command

---

docs/changelog.rst
docs/documentation/hacking.rst
tests/end2end/features/api/prompt.feature
tests/end2end/features/api/test_prompt_bdd.py
tests/end2end/features/conftest.py
tests/end2end/features/image/write.feature
tests/unit/api/test_prompt.py
tests/unit/api/test_settings.py
vimiv/api/__init__.py
vimiv/api/prompt.py
vimiv/api/settings.py
vimiv/config/_style_options.py
vimiv/gui/mainwindow.py
vimiv/gui/prompt.py
vimiv/imutils/_file_handler.py

The prompt is displayed in the bottom-left above the statusbar and asks the user a simple yes/no/abort question. It can be started with the ``api.prompt.ask_question`` function. In addition there is the new ``PromptSetting`` type which is essentially a boolean setting with the additional ``ask`` value. When set to ``ask``, the user is prompted everytime the boolean value of this setting is requested.
This new setting is now used for ``image.autowrite`` defaulting to ``ask``. This should help resolve the issue mentioned by @symbioquine in https://github.com/karlch/vimiv/issues/48.
Here is an image of how this looks in action:
As I see no further issues with the default settings, fixes #169.

Add prompt to ask the user for confirmation

---

tests/conftest.py
tests/unit/utils/test_log.py
vimiv/utils/log.py

As the log level for module-based loggers was only configured in `setup_logging` which is called upon startup, the log level of module-loggers for modules loaded later was always the default `logging.WARNING`. This is fixed by also setting the correct level when creating a new logger. The actual changes in the `utils.log` module are small, but quite some unit tests were added to check this behaviour.
Fixes #172.

Fix logging for lazy-loaded modules

---

docs/changelog.rst
tests/end2end/features/image/imagescroll.feature
tests/end2end/features/image/test_imagescroll_bdd.py
vimiv/gui/image.py

* Zoom now always uses the center of the displayed area as focal-point.
* The image is no longer centered on resize, irrespective of the current scroll position.

Correctly set image focal-point

---

docs/changelog.rst
tests/end2end/features/commandline/test_commandline_bdd.py
tests/end2end/features/conftest.py
tests/end2end/features/misc/test_keyhint_bdd.py
tests/end2end/features/statusbar/message.feature
tests/end2end/features/statusbar/test_message_bdd.py
vimiv/completion/completer.py
vimiv/gui/bar.py
vimiv/gui/command_widget.py
vimiv/gui/commandline.py
vimiv/gui/completionwidget.py
vimiv/gui/keyhint_widget.py
vimiv/gui/mainwindow.py
vimiv/gui/message.py
vimiv/gui/statusbar.py

The bar is now only the statusbar, decoupled from messages and the commandline. This allows treating hide/show separately for the `statusbar.show` setting, displaying a message and entering the command line. In addition the image does not move whenever we show a message / command mode, independent of the statusbar visibility and messages properly overlay the widgets in manipulate mode.

Refactor class hierarchy of the (status-) bar

---

tests/end2end/features/library/libraryscroll.feature
vimiv/gui/library.py

This fixes jumping to the first row in case we delete e.g. the current directory or the last image file.

Also keep library row when last path was removed

---

tests/end2end/conftest.py
tests/end2end/features/image/test_slideshow_bdd.py
tests/end2end/mockdecorators.py
vimiv/api/commands.py
vimiv/api/objreg.py
vimiv/api/status.py
vimiv/gui/image.py
vimiv/gui/mainwindow.py
vimiv/gui/manipulate.py
vimiv/imutils/filelist.py
vimiv/imutils/slideshow.py

Where possible in a simple way we removed using `class.instance` to get the current instance of a class in the `objreg` in unrelated parts of the code. This makes the dependencies clearer and makes calling `class.instance` an implementation detail of the object registry that is not recommended. This should also make refactoring in the future easier.

Reduce the uses of class.instance for classes in objreg

---

AUTHORS
vimiv/api/settings.py
vimiv/imutils/exif.py

Related to #100. I do not think that there is one set of metadata which suit the need to all users. Neither do I think that all users want to fiddle with the source code in order to get their desired metadata to show. Therefore I have added an option to set the desired metadata as a list in the settings.
Since the data is treated generically, I have not yet figured out the best was to properly format the data, e.g. add units, as `piexif` does not seem to have a notion of the units themselves.
Furthermore, depending on the stage of my photography workflow, different metadata information are relevant. Therefore I have thought about adding 3 to 5 user customizable sets of metadata key, which can be viewed one the metadata widget. Changing the metadata set should be done using a shortcut …

Metadata Handling

---

vimiv/api/settings.py
vimiv/config/configfile.py
vimiv/gui/metadatawidget.py
vimiv/imutils/exif.py

As described in #213, this PR implements several customizable sets of metadata keys which are displayed in the `gui.metadatawidget`. The different sets can be accessed and switched by pressing `[count]i`.
The implementation is very similar to how you suggested to implement it in #213. So far, the basic mechanism for reading the keysets from the config, displaying the appropriate metadata in the `gui.metadatawidget` as well as switching the sets using `[count]i` is implemented.  Does it suit your imagination @karlch ?
An open question I have is, how and what default should be provided? Is a single set sufficient (similarly to how it is currently on master)? If yes, I guess we can simply assign that default to `metadata.current_keyset`, since this value should not we changed if …

Mutiple Sets of Metadata

---

vimiv/config/configfile.py

This changes the formatting of the `METADATA` section in the default config file which is written upon first start from:
```
[METADATA]
current_keyset = Make, Model, DateTime, ExposureTime, FNumber, IsoSpeedRatings, FocalLength, LensMake, LensModel, ExposureBiasValue
```
to:
```
[METADATA]
keys1 = Make, Model, DateTime, ExposureTime, FNumber, IsoSpeedRatings, FocalLength, LensMake, LensModel, ExposureBiasValue
keys2 = ExposureTime, FNumber, IsoSpeedRatings, FocalLength
keys3 = Artist, Copyright
```
I noticed this when playing around with the recently merged #215 and feel like this change improves self-documentation and makes the intention of how to use these slightly clearer.
What do you think @jeanggi90?

Write metadata key sets to initial config file

---

tests/end2end/features/image/conftest.py
tests/end2end/features/image/metadata.feature
tests/end2end/features/image/test_metadata_bdd.py
tests/end2end/features/image/test_write_bdd.py
vimiv/gui/metadatawidget.py

This PR adds a few more end2end tests for the `:metadata` command.
In addition to the simple visibility checks we now ensure:
* the correct exif information is 
* we can switch exif information using the different key sets and `:[count]metadata`
* invalid `[count]`s trigger the appropriate error message
* the metadata widget updates its content when the image is changed
For this we did a few things:
1. Do some pytest fixture magic to make the `I add exif information` `when` step available for all tests in the image directory. We now use it in both `metadata.feature` and `write.feature`.
2. Extend the exif content in this fixture so we have a bit of information for each metadata key set.
3. Add two more `then` steps to check the text of the metadata widget.
4. Profit by extending the …

Extend end2end tests for the :metadata command

---

tests/end2end/features/image/conftest.py
tests/end2end/features/image/metadata.feature

Seems like the issue was writing the exif data while thumbnails are being created. This changes the files byte data and can crash QImageReader.  Let's hope this is really the issue :smile: 
fixes #226

Fix metadata test flakiness

---

tests/unit/utils/test_trash_manager.py
vimiv/commands/delete_command.py
vimiv/startup.py
vimiv/utils/trash_manager.py

* Split the command implementation from the trash manager
* Use configparser to read and write trash info files
* Extend and clean up unit tests
fixes #232

Refactor trash manager and delete commands

---

.gitignore
pytest.ini
tests/conftest.py
tests/end2end/conftest.py
tests/end2end/features/image/gif.feature
tests/end2end/features/image/svg.feature
tests/end2end/features/image/test_gif_bdd.py
tests/end2end/features/image/test_svg_bdd.py

Implements end2end tests for animated gifs and svg files.The corresponding files are currently retrieved from the web once in case they are not available. This does not increase the repo size with unnecessary binary files, but may turn out not to be stable enough. In this case we will have to commit the test data folder.

Add tests for animated gifs and vector graphics

---

tests/conftest.py
tests/end2end/conftest.py
tests/end2end/features/command/test_expand_wildcards_bdd.py
tests/end2end/features/conftest.py
tests/end2end/features/image/test_imageopen_bdd.py
tests/integration/conftest.py
tests/integration/test_read_bindings.py
tests/integration/test_read_settings.py
tests/unit/api/test_mark.py
tests/unit/commands/test_history.py
tests/unit/config/test_config.py
tests/unit/config/test_external_configparser.py
tests/unit/config/test_styles.py
tests/unit/utils/test_files.py
tests/unit/utils/test_migration.py
tests/unit/utils/test_thumbnail_manager.py
tests/unit/utils/test_trash_manager.py
tests/unit/utils/test_utils.py
tests/unit/utils/test_xdg.py

As we can infer from https://github.com/pytest-dev/pytest/issues/7259 or https://github.com/pytest-dev/pytest/projects/4 the long-term plan for pytest is to replace any use of `py.path` with the now standard-library module `pathlib`. This removes any uses of the `tmpdir` fixture and replaces it with the corresponding calls using `tmp_path` to avoid any surprises in the future.

Tests: use the tmp_path fixture instead of tmpdir

---

docs/changelog.rst
scripts/vimiv_history.py
tests/end2end/features/commandline/commandline.feature
tests/unit/commands/test_history.py
tests/unit/commands/test_history_deque.py
vimiv/commands/history.py
vimiv/gui/commandline.py

Implements mode based history.
* History is now saved in a json file instead of plain-text.
* History-related commands (`:history` and `:history-substr-search`) now take into account the mode from which we entered the command-line.
* Parts of the command-line, especially history, are now only initialized upon first entry. Therefore the slightly more expensive history reading does not slow down the startup.
* `scripts/vimiv_history.py` is provided to print history of a single mode to stdout. This can be used as a script/reference in case the plain-text nature of the history file was used in any user-scripts.
I will leave this open for a few days for further thinking as we should fix the history format before releasing `1.0` and having it tested in a release before this would be nice.
fixes …

Make history mode based

---

docs/changelog.rst
docs/documentation/configuration/keybindings.rst
tests/integration/test_read_bindings.py
vimiv/config/configcommands.py
vimiv/config/keyfile.py

Instead of using `nop` to remove default bindings we can now use `del-binding`. `nop` is a command in itself that does nothing. Keeping this in addition is useful to ensure e.g. some default qt bindings do nothing.
@schyzophrene-asynchrone what do you think about this? Do you have a better name than `del-binding` in mind? If you are fine with this implementation, I would go ahead and update the documentation accordingly and then merge.
EDIT: Renamed `del-binding` to `unbind`.
fixes #249

Add option to delete binding via keys.conf

---

tests/end2end/features/image/metadata.feature
vimiv/gui/metadatawidget.py

As discussed in #221 
I have already implemented the first todo. Concerning the second one (the one I have proposed in #211), I am not sure if this option is really required. Personally, I am fine not showing anything for missing value. But if there is demand for such an option, I can easiliy add it.
implements #221

Handle Missing Metadata in Widget

---

tests/unit/utils/test_trie.py
vimiv/api/keybindings.py
vimiv/config/configcommands.py
vimiv/config/keyfile.py
vimiv/utils/trie.py

Since you said where and what to change, I thought I could as well try to do it.
So I made the `Trie.check` you spoke about and removed warnings from `__setitem__`. I’m not totally satisfied with what I came with since we have now only one type of warning (the “hides longer key” type) and from a user perspective, they’re the least useful (when you want to keep the short key but don’t know what the longer one is). But since Trie object don’t have a `parent` attribute, I guess I can’t help it.
This is my first pull request on Github, and I’ve discovered what a digital tree was with your code. My changes are small, but I hope they do what they are supposed to and fit to the general code design you adopted for your project. Any comments are welcome.
Issue #270

Checks for binding conflicts only after reading keys.conf or using :bind

---

vimiv/api/__init__.py
vimiv/imutils/_file_handler.py
vimiv/utils/files.py

Currently, the plugin `imageformats` fails to open cr2 Raw files. Therefore, I have decided to implement another raw filetype plugin ([see here](https://github.com/jeanggi90/RawPrev)). It follows the idea proposed and discussed in #16 and displays the jpge thumbnail extracted from the Raw.
The make such a plugin work, I had to create a suitable interface within vimiv. My idea was to have a list (`api.external_hander`) to which plugins which want to provide support for additional file types, can add a tuple of the following format: The first value is a list of filetypes which this plugin support. The second value is a callable, which returns an instance of `Pixmap`, containing the image to open.
In `imutils/_file_handler` there is a check which determines whether the type of the current …

Interface for External Filetype Handler

---

vimiv/api/__init__.py
vimiv/utils/files.py
vimiv/utils/imagereader.py

To finish up #282 and a655a71cd61ffce6d9951640b474833b95562131 I have added a convenience function to the API which allows to add support for new file types using:
```
api.add_external_format(fmt="cr2", test_func=test_cr2, load_func=load_cr2)
```
instead of:
```
files.add_image_format("cr2", test_cr2)
api.external_handler["cr2"] = load_cr2
api.external_handler["CR2"] = load_cr2
```
Further, I have moved the `external_handler` dictionary from `vimiv/api/__init__` to `vimiv/utils/imagereader` since there is no need for it to be exposed via the api. @karlch if you think there is a better place for the `external_handler` dict let me know.

API convenience function for adding filetype support

---

docs/changelog.rst
tests/end2end/features/image/imagezoom.feature
vimiv/api/signals.py
vimiv/gui/image.py
vimiv/imutils/_file_handler.py
vimiv/imutils/filelist.py

Adds a `--keep-zoom` flag to the `:next` and `:prev` command which preserves the zoom level and scroll position of the current image.
This was very easy to implement as all of the logic was already there, just hidden in form of a `reload_only` argument.
@jcjgraf would you like to give this a shot before I merge? Hope you don't mind me dashing ahead here, as you can see the code for this was more or less already in-place.

Add --keep-zoom flag for :next and :prev

---

vimiv/api/_mark.py
vimiv/gui/thumbnail.py

When an image is marked in thumbnail mode, the view is repainted right after each mark. This makes marking of many images (e.g. `:mark *` in thumbnail view painfully slow (~55s for ~1350 images). During that time the GUI is also blocked and unresponsive.
To improve that, we add an additional signal which is broadcast from mark methods in `api._mark` once they are done marking all images. This way clients can prolong the expensive repainting.
This change improves the speed a lot (fraction of a second for ~1350 images).
@karlch if you belief that his is the wrong way to fix this problem and you have got a better idea let me know.
**EDIT**
Argh, this pipeline again :unamused:

Mark Speed in Thumbnail Mode

---

docs/changelog.rst
docs/documentation/exif.rst
tests/end2end/features/image/metadata.feature
tests/unit/imutils/test_exif.py
tests/unit/utils/test_utils.py
vimiv/gui/metadatawidget.py
vimiv/imutils/exif.py
vimiv/utils/__init__.py

Introduces a new `:metadata-list-keys` command to display all valid exif keys for the current image.
I decided to implement this as a standalone command instead of an option for `:metadata` as there are two optional arguments for `:metadata-list-keys`:
- `--n-cols` to customize the number of columns used to format the html table
- `--to-term` to print to the terminal instead of displaying the table in case one would like to easily copy / format / pick ...
These would otherwise just clutter the `:metadata` command.
@jcjgraf what do you think? One point where I would like to hear your opinion is that I removed all keys which are plain hex digits, like `Exif.CanonCs.0x0006`, I suppose this makes sense?
fixes #220

Add :metadata-list-keys command

---

tests/end2end/features/image/conftest.py
tests/end2end/features/image/metadata.feature
vimiv/api/settings.py

After merging #311 I thought it is a good time to rework the default metadata keys. Now there are a total of 5 sets which contain the following information:
1. General information about the image
2. Exif camera settings
3. GPS information
4. IPTC data
5. Technical details about the image
I am really happy with the capabilities of metadata widget. But in the set 5 I wanted to present information like color space, image resolution, image format, image size etc. But, not all of these information are stored in exif (or some only for uncompressed files). To get these information into the metadata widget, I thought that we may extend the `ExifHandler` to accept some custom keys, which are dealt with by vimiv itself and not my exiv2. Concretely, I have thought about the following keys:
- …

Update Metadata Default Keys

---

docs/changelog.rst
tests/unit/api/test_mark.py
vimiv/api/_mark.py

The mark command has been extended with an optional action argument that allows forcing to (un-) mark the passed paths instead of toggling. When used in plugins, one would do
```python
api.mark.mark(paths, api.mark.Action.Mark)  # Force marking
api.mark.mark(paths, api.mark.Action.Unmark)  # Force unmarking
```
for the respective options. This should hopefully deal with all possible use-cases, and always emits `markdone` once done handling all paths. If only a single path should be marked, one can wrap it into a list, i.e.
```python
api.mark.mark([path])  # Toggle mark status of the single path
```
In addition we expose the simple `mark.is_marked` function as proposed.
@jcjgraf does this fulfill your expectations for the first point in #323? :blush:
As I guess the ideas come from the …

Extend mark api

---

vimiv/utils/trash_manager.py

The check `os.path.exists(trash_filename)` fails for broken symlinks (returns false). Therefore, vimiv was unable to undelete symlinks to images. An additional call to `os.path.islink(trash_filename)` fixes that issue.

Undelete Failed to Restore Symlinks

---

vimiv/plugins/imageformats.py

I have not tested this, nor did I find any documentation regarding the bytes header of an avif file.
What I did was downloading images from https://github.com/AOMediaCodec/av1-avif and testing them with `hexdump -n 16 -C`. All of them, except for two with animated features, have a `ftypavif` in byte range 4-12. The two animated have a `ftypavis` in the same range.
[It would seem](https://stackoverflow.com/a/66239407) that some avif files could have another bytes header, but I could not find any relevant document about this.
#338

Add support for detecting .avif files using imageformats plugin

---

docs/changelog.rst
docs/documentation/exif.rst
docs/documentation/install.rst
docs/documentation/pyexiv2.rst

I have just noted that the link to the pyexiv2 project in the documentation is actually wrong. The reason being is that there are (at least) three projects called pyexiv2 (or very similar). We are using [this](https://python3-exiv2.readthedocs.io). I have fixed the URL and added a note to the docs that one has to take care to install the right package.
~I am not sure how to compile and preview the docs locally. So, I cannot guarantee that I did everything right with the warning.~ **Edit:** I just should looked at you contribution guideline in the first place :see_no_evil: 
@karlch feel free to rewrite and change things you do not like.

Wrong URL to pyexiv2 project

---

docs/changelog.rst
tests/end2end/features/misc/clipboard.feature
tests/end2end/features/misc/conftest.py
vimiv/api/_modules.py

Adds a new command `copy-image` to copy the whole image pixmap to the system clipboard, allowing easy pasting to other applications. `yi` and `yI` are currently bound to this command (global clipboard and selection clipboard respectively). 
Todo:
Implements: #358

Copy Image to Clipboard

---

docs/changelog.rst
tests/end2end/features/edit/manipulate.feature
tests/end2end/features/edit/transform.feature
tests/end2end/features/image/imagedelete.feature
vimiv/api/_modules.py
vimiv/api/commands.py
vimiv/api/modes.py
vimiv/api/settings.py
vimiv/commands/delete_command.py
vimiv/gui/image.py
vimiv/imutils/_file_handler.py
vimiv/imutils/imtransform.py

As described in #368 this adds a new `read_only` setting. When active, all commands that may write changes to disk are disabled.
I decided to implement this as a setting instead of a plain parser flag, as settings are nicely available everywhere using the existing settings api. I have to admit that `vimiv -s read_only true` or `vimiv -s read_only 1` is certainly more typing than a simple `vimiv -R` though. @willemw12, do you think the flag should be added in addition? I usually prefer not to do this, as it becomes difficult to decide which settings should also have parser flags, and which should not.
Another open question is how to deal with shell commands. Currently both `:!` and `:spawn` are available when `read_only` is active. This is somewhat borderline as they can obviously make …

Add read only setting

---

docs/changelog.rst
docs/documentation/exif.rst
vimiv/imutils/exif.py

Upon loading metadata information of a image with a type not supported by `piexif` a not caught exception was raised.
Fixes #370 
Thanks @BachoSeven for pointing this out!
@karlch  If you find the warning too verbose we can also get rid of it.

FIX: Piexif unsupported filetype

---

docs/documentation/configuration/plugins.rst

I have written a little plugin which adds *Video Support* to vimiv. Videos are listed within vimiv (this way i do not miss then when copying images from my SD card using vimiv :blush:) and can be played using an external player like MPV or something.
At the time, only QuickTime Movie (`.mov`) is supported but I intend to add new formats soon.
P.S. is there a particular reason why in the docs the default plugins are listed in a table and the user plugins in a list? I think a table looks much nicer.

Mention new Video plugin in docs

---

vimiv/gui/metadatawidget.py

I forgot to update the docstring of the metadata command when improving the default keysets in c5943e8118ec6655f30bd772adb4239ce7541c2a

FIX: number of default keysets for the metadata command

---

docs/changelog.rst
tests/end2end/features/api/print.feature
tests/end2end/features/api/test_print_bdd.py
vimiv/api/_modules.py
vimiv/commands/aliases.py

Adds the new command `print-stdout` to print to STDOUT from within vimiv, and an alias to print all marked images.
~Implements #379~

Command to print to STDOUT

---

docs/changelog.rst
vimiv/gui/library.py

As this has come up both in #136 and in the recent youtube video, I went ahead and changed the behaviour of scrolling with the mouse in the library. Instead of just scrolling the view, it now changes the selection. Personally I have no preference, as I almost never use the mouse, and felt one can always click wherever one wants when scrolling the view.
@jcjgraf @BachoSeven any thoughts if this version would be preferable?

Change mouse scroll behaviour in library

---

docs/changelog.rst
tests/end2end/features/misc/startup.feature
tests/end2end/features/misc/teardown.feature
tests/end2end/features/misc/test_startup_bdd.py
tests/end2end/features/misc/test_teardown_bdd.py
vimiv/parser.py
vimiv/startup.py

After better understanding the idea behind #379 I went ahead and added the `-i` and `-o` flags. The described workflow with "vimiv as pipe" to select images should now be possible using:
```bash
SELECTED=$(find images -type f | vimiv -i -o "%m" --command "enter thumbnail")
```
Any feedback would be welcome @jcjgraf and @loiccoyle as I don't really use this type of a workflow myself :blush:
TODO:

Vimiv as pipe

---

docs/changelog.rst
tests/unit/test_parser.py
vimiv/app.py
vimiv/parser.py
vimiv/startup.py

This is a possible solution to #384 which can now be done by starting vimiv with `--qt-args '--name WM_CLASS_INSTANCE'`. The implementation here is nowhere near as complete as the one of qutebrowser, but worked fine for the simple use-cases I could think of. With this, we could even deprecate / remove the `--geometry` flag as this is now possible using `--qt-args '--geometry WIDTHxHEIGHT'`. All of this would certainly benefit from some additional examples as described in #382.
@loiccoyle maybe you could give this a try as it is based on your idea?
Fixes #384.

Add commandline flag to pass arguments directly to qt

---

docs/changelog.rst
vimiv/gui/library.py
vimiv/gui/thumbnail.py
vimiv/widgets.py

I feel like this is a bit of a no-brainer, but missed this somehow when implementing the new scroll behaviour in the library in #378. Thumbnail mode now reflects these changes as well and also changes the selection when scrolling with the mouse.
Any thoughts or objections @jcjgraf @BachoSeven?

Adopt mouse scroll behaviour of library mode for thumbnail mode

---

docs/changelog.rst
vimiv/api/settings.py
vimiv/gui/thumbnail.py
vimiv/imutils/filelist.py

There were some inconsistencies between the base modules and some thumbnail-* modules. Namely, `basename` contained the file extension while it was striped for `thumbnail-name`, and `index` was zero padded while `thumbnail-index` was not.
The first point was fixed by distinguishing between `name` (name w/o extension), `basename` (name w extension) and `extension` (i.e. adding seperate modules for each of them).
The default statusbar module for `left_thumbnail` was changed from `thumbnail-name` to `thumbnail-basename` to be consistent with `left_image`.
@karlch feel free to merge if you agree

Fix statusbar inconsistencies

---

tests/end2end/features/misc/symlink.feature
tests/end2end/features/misc/test_symlink_bdd.py
vimiv/api/commands.py
vimiv/api/working_directory.py
vimiv/completion/completionmodels.py
vimiv/gui/library.py
vimiv/imutils/filelist.py
vimiv/parser.py
vimiv/utils/files.py

The new usage of realpath introduced in 0cc236327662dbf18c5f1d82cee287941d4e1350 also introduced a new bug. The image filelist would load both the symlink and the original image, even if they are not in the same directory. This PR attempts to save this issue while also fixing the initial issue that the mentioned commit tried to address.
Related to #374

Fix showing both real and symlink image from different directories

---

docs/changelog.rst
docs/documentation/configuration/plugins.rst
vimiv/plugins/imageformats.py

To enable `jp2` support via the imageformats plugin, add
```
imageformats = jp2
```
to the `[PLUGINS]` section of your `vimiv.conf`. This requires the qt imageformats plugin for `jp2` support in qt.
@szsdk could you give this a shot with some of your `jp2` files? I have had limited success with the samples I found online (one worked, one didn't :sweat_smile:), but obviously the sample size was rather tiny..

Add support for jp2 via imageformats plugin

---

docs/changelog.rst
vimiv/api/settings.py
vimiv/gui/image.py

The new `image.zoom_wheel_ctrl` setting defines if the user needs to hold the `<ctrl>` modifier to zoom the current image. The default is `True` to keep the current behaviour.
fixes #448

Add setting to toggle need of ctrl for wheel-zoom

---

docs/changelog.rst
vimiv/commands/delete_command.py

When added, the user will be prompted for confirmation before the delete
is executed.
fixes #446

Add --ask flag to :delete command

---

misc/vimiv.1
vimiv/parser.py

missed that in #381
P.S. I am not sure where the `optional argument` -> `options` change comes from... Probably something was changed but the man page not rebuild, I guess

Add missing metavar for --output argument

---

vimiv/utils/files.py

It appears that QImageReader can handle ICO files out of the box. So, only the file type check had to be adapted
@TornaxO7 could you check if it  works for you (make sure to disable your ico plugin)
closes #483

Filesupport for ICO files

---

.github/workflows/ci.yml
tox.ini
vimiv/gui/metadatawidget.py

We now combine coverage of the test suite without exif support, and the one using piexif. This can be extended to other Qt versions, other dependencies, ... in the future.

CI: Make use of codecov report merging

---

.github/workflows/ci.yml
.github/workflows/docs.yml

Improve github workflows in various ways.
1. Remove a lot of code duplication in the github workflow file by using a single matrix job. This should definitely simplify things going forward with new python, pyqt, and other versions.
2. Use the cache action to cache setup.
3. Reduce timeout minutes as our tests are typically fast, except for the still mysterious #335.

Improve github workflows

---

.github/workflows/ci.yml
vimiv/plugins/metadata_pyexiv2.py

Re-enables CI for pyexiv2 on python 3.8.
No idea what to do once we drop support for python 3.8 in a year or so, but at least for now this allows us to continue testing pyexiv2.

Enable CI for pyexiv2

---

AUTHORS
docs/changelog.rst
docs/documentation/configuration/settings.rst
tests/end2end/features/image/imageorder.feature
tests/unit/api/test_settings.py
vimiv/api/settings.py

Starting with what I consider to be one of the simplest changes discussed in #651 and as always, nothing is as simple as expected.
It works pretty much as discussed, but it's worth noting that I found reversing the sort order does not work, probably because `lambda x: 0` doesn't provide the sorting algorithm varied numbers to meaningfully reverse. I toyed around with ways of making reversing work, but figured I'd stay with the agreed upon approach of keeping this setting simple for now.
---
For sort 'image_order' and 'directory_order', the 'none' setting can be used to allow images to follow the last order they were encountered in by the software, instead of re-sorting.
Note that setting another sorting mode while the software is running then switching back to 'none' will see files remain …

Add the 'none' sorting setting

---

docs/documentation/install.rst
docs/documentation/updating_icon_cache.rst
misc/Makefile

Today I spent about two hours searching why when installing `vimiv-qt` manually (using `sudo make install`), vimiv's icon wouldn't appear in my application launcher (wofi).
According to [wofi man page](https://man.archlinux.org/man/wofi.7.en):
> When images are enabled drun mode will pull icon themes however being a GTK app it's possible you'll need to run gtk-update-icon-cache to get them to apply.
Then after searching about how to use `gtk-update-icon-cache` [[1]](https://manpages.ubuntu.com/manpages/xenial/man1/gtk-update-icon-cache.1.html) [[2]](https://man.archlinux.org/man/gtk4-update-icon-cache.1.en), I came up with this fix.
As I don't know if every system contains `gtk-update-icon-cache`, I allowed the command to fail by prepending it with `-`.
Hope this is an acceptable change.

Update icons cache on manual install

---

docs/changelog.rst
tests/integration/test_read_settings.py
tests/unit/utils/test_thumbnail_manager.py
vimiv/api/settings.py
vimiv/utils/thumbnail_manager.py

Continuing #651 changes. Also, the `check_thumbails_created` in `tests/unit/utils/test_thumbnail_manager.py` might be a typo. Figured this should probably be another pull request or quick commit from maintainers, though.
---
If this option is set to False, then do not save newly-generated thumbnails to the disk. Previously saved thumbnail images will be used normally and will never be deleted.
This saves space and reduces drive writes at the cost of extra computational overhead by making the original image be reopened each time the thumbnail is loaded.

Add thumbnail.save configuration option.

---

misc/requirements/requirements_lint.txt
tests/unit/utils/test_utils.py
tox.ini

fixes #661 
Decided to keep the (few) pylint formatting issues, as they do sometimes make it easier to detect the change (e.g. for trailing whitespace) and the additional noise doesn't seem too bad.

CI: Replace pycodestyle with black

---

docs/changelog.rst
vimiv/utils/log.py

This allows us to also suppress various Qt messages.
fixes #601
@jcjgraf @Yutsuten could one of you give it a quick shot, e.g. with `vimiv --log-level error`. For me, a libpng warning is now successfully suppressed :blush:

Disable qt logging at higher log levels

---

docs/documentation/hacking.rst
tests/end2end/features/image/test_imageopen_bdd.py
tests/end2end/features/plugins/test_plugins_bdd.py
tests/unit/conftest.py
tests/unit/utils/test_files.py
tests/unit/utils/test_imageheader.py
vimiv/api/__init__.py
vimiv/plugins/imageformats.py
vimiv/utils/files.py
vimiv/utils/imageheader.py
vimiv/utils/imagereader.py

replaces #646 
Since imghdr is getting deprecated from the standard library (see #579), this PR replaces that module by a own (and thereby, legally completely decoupled independent (unlike in #646)), implementation of the magic byte file type detection.
Some advantages of this approach, over using the package:
- Detect (all) file types which are actually supported by QT natively or extended (by using qtiamgeformats)
- Well, some are not detectable...
- Detect none which are not supported
- Have a central place for all magic byte checks
- Cleanup of `utils/files` and `plugin/imageformats`
- Well structured magic byte checks allows for better maintainability
- `plugin/imageformats` has a specific and well defined purpose
- I.e. enable image type support that require the (manual) …

Replace imghdr

---

docs/changelog.rst
vimiv/utils/imageheader.py

All XML files were detected as SVGs. This bug has been in vimiv ever since SVGs are supported (441b2d). Stupidly, I just copied to old SVG check function in #650 without thinking 😬
A xml file (i.e. a file starting with `<?xml`) is a svg, if and only if it is followed by a `<svg` tag[1].
[1] Do not quote me on this, standards are weird and the signature differentiates between different SVG standard versions. It is likely that we still have false negative rate, but we better only extend the detected signatures once we encounter such samples out in the wild...

Fix all XML files detected as SVG

---

vimiv/gui/eventhandler.py

Allows to bind `<delete>`, as suggested in https://github.com/karlch/vimiv-qt/issues/682#issuecomment-1675769321
Should fix #682, works fine on my end

Add `Qt.Key_Delete` to `special_keys` dict

---

docs/changelog.rst
vimiv/utils/imageheader.py

I have just come across a JPEG what was not detected by vimiv. I have adapted the check function to also detect that image as a valid JPEG.
At the same time I had to realize that the detection of JPEGs is not as straight-forward as for other file formats. That is because JPEG is itself not a file format, but only a standard for the used compression function. The two most common JPEG file formats are JPEG/JFIF and JPEG/Exif. But every manufacturer can create their own JPEG-based file formats. Therefore, there are many different JPEG-based file formats which are different in their structure. (Obviously) There is also no central place to get information about all available formats.
JPEGs are a list of segments. Each segments starts with a 1 byte marker. Each marker is preceded by byte …

Improve JPEG Header Detection

---

docs/changelog.rst
tests/end2end/features/api/mark.feature
tests/end2end/features/api/test_mark_bdd.py
vimiv/api/_mark.py

It is possible to insert empty lines into the tag files. Once the tagged images of that tag are loaded again, an empty string is inserted into the marked list. This leads to issues (e.g. `:open :m` fails).
Simply run `:tag-write test` multiple times without adding marking a new image in-between.
- Prevent insertion of empty lines into the tag file: 3561980c3a61f2e615c6009bfd2b65cf4400e7bb
- Prevent empty line getting read tags: 9b657c44979253e24147d8f94afa323a338eae9c [1]
[1] 96abdba02681d0f6716e8b4b00f38359555e4efa would also have fixed the second point. But I added that commit rather to get rid of repeated code. In addition, it ensures that images loaded from the tag are actually also added to the watcher, which they are not without this commit.

Fix empty lines in tag file  

---

docs/documentation/configuration/plugins.rst

We also mentione the default path of `XDG_CACHE_HOME` at several places in the docs (e.g. [here](https://github.com/karlch/vimiv-qt/blob/master/docs/documentation/configuration/settings.rst)), therfore we could also mentione it for `XDG_DATE_HOME`.
Is an attempt to fix the confusion raised in #712
fix #712

DOCS Indicate default path for XDG_DATA_HOME

---

vimiv/utils/imageheader.py

Indeed, there are (actually many) SVGs that do not start with a `<?` header but simply `<svg`. I have added detection for them.Though, I still did not manage to find documentation on all possible header of SVG files. What when the `<svg` line is preceded by a comment line? `file` detects such SVGs as HTML.
@infinitewhileloop Thanks for reporting and the submission of the sample.
fixes #748

Detect SVGs that do not start with a header

---

misc/vimiv.desktop

Closes #754 (Oops, I forgot to add this in the commit message)
Supported formats according to [this](https://github.com/karlch/vimiv-qt/blob/master/vimiv/utils/imageheader.py#L11C1-L25C85) (referring to [the comment](https://github.com/karlch/vimiv-qt/issues/754#issuecomment-1856502245)) are added in the desktop entry file.
I have included the formats supported by the `qtimageformats` module. If that's an issue, I think it can be mitigated by showing a in-program warning to install optional dependencies. However, not including them will not solve the issue and can't be mitigated later.

Add more supported formats in vimiv.desktop

---

vimiv/api/signals.py
vimiv/commands/search.py
vimiv/gui/eventhandler.py

This allows plugins to connect to a generic cancel signal. Currently used to reset partial keys and clear search.
Supersedes #691 as the command was finally not considered useful, but having the signal definitely is.

Implement cancel signal emitted by <escape>

---

tests/end2end/features/image/metadata.feature
vimiv/plugins/metadata_pyexiv2.py

Catches additional exceptions when reading metadata with py3exiv2.
fixes #803

Fix py3exiv2 svg crash

---

tests/unit/gui/test_eventhandler.py
vimiv/gui/eventhandler.py

Neither semicolon `;` nor the number symbol `#` could be bound as they were parsed by configparser as a comment. Fixed by allowing to bind these via <semicolon> and <number> instead.
fixes #845

Fix binding of configparser comment chars
